name: event
description: Create lightweight custom Events, that allow interested subscribers to be notified that something has happened.
version: 2.0.0
homepage: https://github.com/aryehof/dart-event

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
