name: event
description: Create lightweight custom Events, that allow interested subscribers to be notified that something has happened.
version: 1.1.5
homepage: https://github.com/aryehof/dart-event

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.0
