name: event
description: Provides for the creation of custom Events, that allow interested subscribers to be notified that something has happened.
  Provides a notification mechanism across independent packages/layers/modules.
version: 1.0.0
homepage: https://github.com/aryehof/event

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
